fpath <- file.path('..', 'orig', 'LR04', 'LR04')
currwd <- getwd()
setwd(fpath)
LR04 <-read.delim("total.tab",skip=58,header=FALSE,col.names=c("Age.ka","Forambenthd18O.permilPDB","d18Ostdev"),sep="")
setwd(currwd)
